-- Supabase SQL Editor'de çalıştırın
-- Bu komut, projects tablosunun eksik kolonlarını tamamlar ve 'schema cache' hatasını çözer.

-- 1. projects tablosunu güvenli bir şekilde güncelle
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

DO $$
BEGIN
    -- name kolonu (Proje Adı)
    ALTER TABLE projects ADD COLUMN IF NOT EXISTS name TEXT;
    
    -- Diğer gerekli kolonlar
    ALTER TABLE projects ADD COLUMN IF NOT EXISTS description TEXT;
    ALTER TABLE projects ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'in_progress';
    ALTER TABLE projects ADD COLUMN IF NOT EXISTS budget NUMERIC;
    ALTER TABLE projects ADD COLUMN IF NOT EXISTS start_date DATE;
    ALTER TABLE projects ADD COLUMN IF NOT EXISTS end_date DATE;
    ALTER TABLE projects ADD COLUMN IF NOT EXISTS priority TEXT DEFAULT 'medium';
    ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_id BIGINT REFERENCES clients(id);
EXCEPTION
    WHEN duplicate_column THEN RAISE NOTICE 'column already exists';
END $$;

-- 2. Eğer tablonuzda 'title' varsa ve 'name' yoksa, verileri taşı (Opsiyonel, varsa çalışır)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='projects' AND column_name='title') THEN
        UPDATE projects SET name = title WHERE name IS NULL;
    END IF;
EXCEPTION
    WHEN OTHERS THEN RAISE NOTICE 'Title migration skipped';
END $$;

-- NOT: Bu işlemi yaptıktan sonra Supabase API Settings -> "Reload Schema Cache" yapmanız gerekebilir.
