-- ⚠️ GÜVENLİ KURULUM: Sadece Posts Tablosu
-- Mevcut tablolarınızı silmez, sadece posts tablosunu oluşturur

-- 1. Önce posts tablosu varsa kaldır (güvenli)
DROP TABLE IF EXISTS posts CASCADE;

-- 2. Posts tablosunu oluştur
CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  excerpt TEXT,
  content TEXT,
  image TEXT,
  category TEXT,
  read_time TEXT DEFAULT '5 dk',
  status TEXT DEFAULT 'published',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 3. RLS (Row Level Security) - Herkese açık (Public)
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

-- Herkes okuyabilir
CREATE POLICY "Public posts are viewable by everyone" 
  ON posts FOR SELECT 
  USING (status = 'published');

-- Herkes ekleyebilir (Admin paneli için - gerçek üretimde kısıtlanmalı)
CREATE POLICY "Public posts are insertable by everyone" 
  ON posts FOR INSERT 
  WITH CHECK (true);

-- Herkes güncelleyebilir (Admin paneli için - gerçek üretimde kısıtlanmalı)
CREATE POLICY "Public posts are updateable by everyone" 
  ON posts FOR UPDATE 
  USING (true);

-- Herkes silebilir (Admin paneli için - gerçek üretimde kısıtlanmalı)
CREATE POLICY "Public posts are deletable by everyone" 
  ON posts FOR DELETE 
  USING (true);

-- 4. Trigger: updated_at otomatik güncelleme
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_posts_updated_at ON posts;
CREATE TRIGGER update_posts_updated_at
    BEFORE UPDATE ON posts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ✅ TAMAMLANDI!
-- Posts tablosu hazır. Artık blog sistemi çalışacak.
