-- Create project_notes table
create table if not exists project_notes (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table project_notes enable row level security;

-- Policies
create policy "Enable read access for all users" on project_notes for select using (true);
create policy "Enable insert for authenticated users only" on project_notes for insert with check (auth.role() = 'authenticated');
create policy "Enable delete for authenticated users only" on project_notes for delete using (auth.role() = 'authenticated');
