-- Tabloları temizle (Gerekirse)
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS posts;

-- 1. Blog Yazıları Tablosu
CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  excerpt TEXT,
  content TEXT,
  image TEXT,
  category TEXT,
  read_time TEXT DEFAULT '5 dk',
  status TEXT DEFAULT 'published',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 2. Portfolyo Projeleri Tablosu
CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  client TEXT,
  category TEXT,
  description TEXT,
  image TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 3. Hizmetler Tablosu
CREATE TABLE services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  descr TEXT, -- 'desc' reserved word olabilir, descr yaptim
  icon TEXT,
  status TEXT DEFAULT 'Aktif',
  views INTEGER DEFAULT 0,
  projects_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 4. İletişim Mesajları Tablosu
CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- RLS (Row Level Security) Politikaları - Şimdilik herkese açık (Public)
-- Gerçek prodüksiyonda burayı kısıtlamak gerekir.
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public posts are viewable by everyone" ON posts FOR SELECT USING (true);
CREATE POLICY "Public posts are insertable by everyone" ON posts FOR INSERT WITH CHECK (true); -- Admin paneli icin gecici
CREATE POLICY "Public posts are updateable by everyone" ON posts FOR UPDATE USING (true);

ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public projects are viewable by everyone" ON projects FOR SELECT USING (true);
CREATE POLICY "Public projects are insertable by everyone" ON projects FOR INSERT WITH CHECK (true);
CREATE POLICY "Public projects are updateable by everyone" ON projects FOR UPDATE USING (true);

ALTER TABLE services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public services are viewable by everyone" ON services FOR SELECT USING (true);
CREATE POLICY "Public services are insertable by everyone" ON services FOR INSERT WITH CHECK (true);
CREATE POLICY "Public services are updateable by everyone" ON services FOR UPDATE USING (true);

ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public messages are insertable by everyone" ON messages FOR INSERT WITH CHECK (true); -- Iletisim formu icin
CREATE POLICY "Public messages are viewable by everyone" ON messages FOR SELECT USING (true); -- Admin paneli icin

